spring:
  datasource:
    url: jdbc:postgresql://10.140.0.3:5432/postgresql
#    url: jdbc:postgresql://localhost:5432/postgresql
    username: test
    password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # rabbitmq
  rabbitmq:
#    host: localhost
    host: 10.146.0.2
    username: guest
    password: guest
    port: 5672